#!/bin/bash
# This script closes STS
MYPID=$$
MYPATH="$(cd "$(dirname "$0")" && pwd)"
MYREALPATH="$(dirname "$(readlink -f "$0")")"
ISSTSON=`$MYREALPATH/sts_ison`
if [ "$ISSTSON" = "0" ]; then
	$MYREALPATH/sts_status
else
	echo -n "closing STS."
	su cmb -c "touch /home/sts/shared/STSCLOSE"
	# Wait at least one minute for it to exit...
	for second in 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 \
		0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 60 ; do
		echo -n "."
		ISSTSON=`$MYREALPATH/sts_ison`
		if [ "$ISSTSON" = "0" ]; then
			break;
		fi
		sleep 1
	done
	if [ "$second" = "60" ]; then
		echo "."
		echo "WARNING:  Gave up waiting for STS to exit!"
		sleep 15
	else
		echo " [closed ]"
	fi
fi
